### ISSUE TITLE
Undefined variable: filename

### ISSUE THREAD

**Issue by mauromangas** [electro-framework/electro#1]
Hi there mate,

When I call a Macro in a view, I get the following error:

PHP Notice

Undefined variable: filename

Thrown from private/plugins/electro-modules/matisse/src/Components/Macro/MacroCall.php, line 86

```php
self::throwUnknownComponent ($this->context, $name, $parent, $filename);
```

We concluded that we should remove the `$filename`.

Thanks :)

**Comment by claudio-silva** [comment]
This has been solved.
