### ISSUE TITLE
Module version in composer.json

### ISSUE THREAD

**Issue by mauromangas** [electro-framework/electro#2]
Hi there,

Running the `make:matisse-module` command or `make:module` command, the module version in the root composer.json is different from the module composer.json.

In the project root composer.json:
`"test/website": "self.version",`

In the module root composer.json:
`"version": "1.0.0",`

In the bash, I get the following error:
```bash
  Problem 1
    - The requested package ninja/site dev-master exists as test/website[1.0.0] but these are rejected by your constraint.
```

I will be grateful for any help you can provide. :)

**Comment by claudio-silva** [comment]
This is no longer applicable to the current version.
