### ISSUE TITLE
Criação de novo método em RedirectionInterface

### ISSUE THREAD

**Issue by tiagomgelias** [electro-framework/electro#6]
Deparei me com a necessidade de fazer um redirect para uma página com parâmetros no URL, e não encontrei um método no RedirectionInterface para facilitar o processo. 
Recomendo criarem um método para tal, por exemplo:

RedirectionInterface::toUrlWithParams($url, array $params, $status);

**Comment by claudio-silva** [comment]
New method `toUrlWithParams()` was added to `RedirectionInterface`.

**Comment by claudio-silva** [comment]
Also changed `NavigationLink->urlOf()` to allow substitution of named route parameters.
