### ISSUE TITLE
Bug at Kernel - onRegisterServices - Electro Beta Version

### ISSUE THREAD

**Issue by tiagomgelias** [electro-framework/electro#8]
Ao querer utilizar uma classe de User de Authentication personalizada e depois ao fazer por exemplo: 

`$session->user(); 
`
Não retorna a minha classe personalizada.

Para resolver, tive que fazer um delegate pela segunda vez (o primeiro está no AuthenticationModule)

```
$kernel->onRegisterServices (
					function (InjectorInterface $injector) {
							$injector
								->delegate (UserInterface::class, function () use ($injector) {
										return $injector->make (Utilizador::class);
								});
					});

```

**Comment by claudio-silva** [comment]
Not reproducible.
